### ISSUE TITLE
I have got exception while building this project, please check

### ISSUE THREAD

**Issue by burkaslarry** [zhukic/Chat-Firebase-Kotlin#2]
I have got exception as below , using Android Studio 3,0.1

Error:No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getGenerateRClassTask() is applicable for argument types: () values: []

**Comment by zhukic** [comment]
Hi, @burkaslarry. Unfortunately, I can't reproduce this error on my Android Studio which running on the same version as your. Sorry for that.
