### ISSUE TITLE
Necessary update

### ISSUE THREAD

**Issue by vczxqn** [zhukic/Chat-Firebase-Kotlin#3]
Hi zhukic, 
Thank you for time to create this project.
Could you update this project to latest android studio and dependencies?
Please to add also image support (upload images to firebase and load them later in chat activity) to this chat.
Thank you for any activity in this awesome project.
Kind regards.

**Comment by zhukic** [comment]
Hi, @vczxqn. Sorry, but this project is not supported anymore. Thanks
